import type { Meta, StoryObj } from "@storybook/react";
import { Badge } from "./Badge";
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Playground: Story;
export declare const High: Story;
export declare const Medium: Story;
export declare const Low: Story;
export declare const Validated: Story;
export declare const Incoming: Story;
export declare const Quarantined: Story;
export declare const Failed: Story;
export declare const Archieved: Story;
export declare const Processor: Story;
export declare const WithIconSuccess: Story;
export declare const WithIconWarning: Story;
export declare const WithIconIncoming: Story;
export declare const WithIconFailed: Story;
export declare const WithIconArchieved: Story;
export declare const Small: Story;
export declare const MediumSize: Story;
export declare const Large: Story;
