import type { Meta, StoryObj } from "@storybook/react-vite";
import { Input } from "./Input";
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const WithIcons: Story;
export declare const Invalid: Story;
export declare const Sizes: Story;
export declare const Disabled: Story;
export declare const ReadOnly: Story;
export declare const Loading: Story;
