import type { Meta, StoryObj } from "@storybook/react";
import { Heading } from "./Heading";
declare const meta: Meta<typeof Heading>;
export default meta;
type Story = StoryObj<typeof Heading>;
export declare const Playground: Story;
export declare const AllHeadingLevels: Story;
export declare const Sizes: Story;
export declare const Weights: Story;
export declare const AsChildLink: Story;
