import type { Meta, StoryObj } from "@storybook/react";
import { InfoCard } from "./InfoCard";
declare const meta: Meta<typeof InfoCard>;
export default meta;
type Story = StoryObj<typeof InfoCard>;
export declare const Playground: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const Orders: Story;
export declare const DarkTheme: Story;
export declare const AsChildLink: Story;
